name = "ywgyw"
main = "src/index.js"
compatibility_date = "2024-03-18"

[[kv_namespaces]]
binding = "IPTV_KV"
id = "4d517e225a12416c8036466eef0543be"

# 新增：配置定时触发器
[triggers]
# "0 */6 * * *" 表示每 6 小时自动执行一次抓取任务
crons = ["0 */6 * * *"]
